
project_id = "vmhxcwaaujznyogxmabq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vmhxcwaaujznyogxmabq.supabase.co"]
jwt_expiry = 3600

[functions.mspace-sms]
verify_jwt = true

[functions.mspace-webhook]
verify_jwt = false
