// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qibtlpukhirmhpgblpht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYnRscHVraGlybWhwZ2JscGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDg1ODgsImV4cCI6MjA2MjE4NDU4OH0.4lvZdO7JfPmuzgyYOIyGTbRwG80yV_5lc-g02hv-LqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);